import js from "@eslint/js";
import gitignore from "eslint-config-flat-gitignore";
import { defineConfig, globalIgnores } from "eslint/config";
import globals from "globals";
import tseslint from "typescript-eslint";

export default defineConfig([
  gitignore(),
  globalIgnores(["spec/"]),
  {
    files: ["**/*.{js,mjs,cjs,ts,mts,cts}"],
    plugins: { js },
    extends: ["js/recommended"],
    languageOptions: { globals: globals.node },
  },
  tseslint.configs.strict,
  tseslint.configs.stylistic,
  {
    files: ["src/client/**/*.ts"],
    rules: {
      // Generated by @hey-api/openapi-ts — uses void in union positions
      // for endpoints with no response body, and dynamic delete/non-null
      // assertion in serialization helpers.
      "@typescript-eslint/no-invalid-void-type": "off",
      "@typescript-eslint/no-dynamic-delete": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
]);
