 
// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client/index.js";
import {
  getSolutionResponseTransformer,
  solveVrpResponseTransformer,
} from "./transformers.gen.js";
import type {
  AsyncClusteringProblemData,
  AsyncClusteringProblemErrors,
  AsyncClusteringProblemResponses,
  AsyncVrpData,
  AsyncVrpErrors,
  AsyncVrpResponses,
  CalculateMatrixData,
  CalculateMatrixResponses,
  CalculateProfileData,
  CalculateProfileResponses,
  DeleteProfileData,
  DeleteProfileResponses,
  GetClusterSolutionData,
  GetClusterSolutionErrors,
  GetClusterSolutionResponses,
  GetGeocodeData,
  GetGeocodeResponses,
  GetIsochroneData,
  GetIsochroneResponses,
  GetMatrixData,
  GetMatrixResponses,
  GetMatrixSolutionData,
  GetMatrixSolutionResponses,
  GetProfileData,
  GetProfileResponses,
  GetProfileSolutionData,
  GetProfileSolutionResponses,
  GetRouteData,
  GetRouteErrors,
  GetRouteResponses,
  GetSolutionData,
  GetSolutionErrors,
  GetSolutionResponses,
  PostGpxData,
  PostGpxResponses,
  PostMatrixData,
  PostMatrixResponses,
  PostProfileData,
  PostProfileResponses,
  PostRouteData,
  PostRouteErrors,
  PostRouteResponses,
  SolveClusteringProblemData,
  SolveClusteringProblemErrors,
  SolveClusteringProblemResponses,
  SolveVrpData,
  SolveVrpErrors,
  SolveVrpResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Calculate a route
 *
 * For the GET request you specify the parameters in the URL and can try it directly in every browser.
 * However, it has some disadvantages when using many points (URL length limit) and the [`custom_model` Feature](#tag/Custom-Model) cannot be used.
 * Therefore, our recommended endpoint is the [POST route endpoint](#operation/postRoute).
 *
 */
export const getRoute = <ThrowOnError extends boolean = false>(
  options: Options<GetRouteData, ThrowOnError>,
): RequestResult<GetRouteResponses, GetRouteErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetRouteResponses,
    GetRouteErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/route",
    ...options,
  });

/**
 * Calculate a route
 *
 * This POST endpoint accepts routing requests as JSON and returns the computed route as JSON. It offers a high degree of customization through the custom model to account for
 * vehicle constraints such as height or weight, avoidance or exclusion of specific areas. It also provids rich route information including elevation data, turn-by-turn instructions,
 * toll information, and other detailed path details.
 *
 */
export const postRoute = <ThrowOnError extends boolean = false>(
  options?: Options<PostRouteData, ThrowOnError>,
): RequestResult<PostRouteResponses, PostRouteErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    PostRouteResponses,
    PostRouteErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/route",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Compute an isochrone
 */
export const getIsochrone = <ThrowOnError extends boolean = false>(
  options: Options<GetIsochroneData, ThrowOnError>,
): RequestResult<GetIsochroneResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<GetIsochroneResponses, unknown, ThrowOnError>({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/isochrone",
    ...options,
  });

/**
 * Compute a matrix
 *
 * For N origins and M destinations, compute routes from all origins to all destinations and output
 * the result as a matrix of travel times and/or distances.
 *
 * This includes the common cases of routes from one origin to many destinations, or from many origins to one
 * destination.
 *
 */
export const getMatrix = <ThrowOnError extends boolean = false>(
  options?: Options<GetMatrixData, ThrowOnError>,
): RequestResult<GetMatrixResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetMatrixResponses, unknown, ThrowOnError>({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/matrix",
    ...options,
  });

/**
 * Compute a matrix
 *
 * Calculate a matrix of travel times and/or distances between N origins and M destinations.
 *
 * This includes the common cases of routes from one origin to many destinations, or from many origins to one
 * destination.
 *
 */
export const postMatrix = <ThrowOnError extends boolean = false>(
  options?: Options<PostMatrixData, ThrowOnError>,
): RequestResult<PostMatrixResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<PostMatrixResponses, unknown, ThrowOnError>({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/matrix",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Submit a matrix computation job
 *
 * An alternate endpoint for computing a large matrix asynchronously, where a request against the regular
 * endpoint would result in a timeout.
 *
 * The request format is the same, but instead of the result, you are given a job identification number that
 * you can use to retrieve the result once it is available.
 *
 * In most cases, prefer the regular endpoints.
 *
 * Here are some full examples via curl:
 * ```bash
 * $ curl -X POST -H "Content-Type: application/json" "https://graphhopper.com/api/1/matrix/calculate?key=[YOUR_KEY]" -d '{"points":[[13.29895,52.48696],[13.370876,52.489575],[13.439026,52.511206]]}'
 * {"job_id":"7ac65787-fb99-4e02-a832-2c3010c70097"}
 * ```
 *
 * Pick the returned `job_id` and use it in the next GET requests:
 * ```bash
 * $ curl -X GET "https://graphhopper.com/api/1/matrix/solution/7ac65787-fb99-4e02-a832-2c3010c70097?key=[YOUR_KEY]"
 * {"status":"waiting"}
 * ```
 *
 * When the calculation is finished (`status:finished`) the JSON response will contain the full matrix JSON under `solution`:
 * ```bash
 * $ curl -X GET "https://graphhopper.com/api/1/matrix/solution/7ac65787-fb99-4e02-a832-2c3010c70097?key=[YOUR_KEY]"
 * {"solution":{"weights":[[0.0,470.453,945.414],[503.793,0.0,580.871],[970.49,569.511,0.0]],"info":{"copyrights":["GraphHopper","OpenStreetMap contributors"]}},"status":"finished"}
 * ```
 *
 * Please note that if an error occured while calculation the JSON will not have a status but contain directly the error message e.g.:
 * ```json
 * {"message":"Cannot find from_points: 1"}
 * ```
 * And the optional `hints` array.
 *
 */
export const calculateMatrix = <ThrowOnError extends boolean = false>(
  options?: Options<CalculateMatrixData, ThrowOnError>,
): RequestResult<CalculateMatrixResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    CalculateMatrixResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/matrix/calculate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Retrieve result of a matrix computation job
 */
export const getMatrixSolution = <ThrowOnError extends boolean = false>(
  options: Options<GetMatrixSolutionData, ThrowOnError>,
): RequestResult<GetMatrixSolutionResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    GetMatrixSolutionResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/matrix/solution/{jobId}",
    ...options,
  });

/**
 * Map-match a GPX file
 *
 * To get a match response you send a GPX file in the body of an HTTP POST request and specify request parameters like the `key` and `profile` in the URL.
 * See below for more supported parameters.
 *
 */
export const postGpx = <ThrowOnError extends boolean = false>(
  options: Options<PostGpxData, ThrowOnError>,
): RequestResult<PostGpxResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<PostGpxResponses, unknown, ThrowOnError>({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/match",
    ...options,
    headers: {
      "Content-Type": "application/gpx+xml",
      ...options.headers,
    },
  });

/**
 * Geocoding Endpoint
 */
export const getGeocode = <ThrowOnError extends boolean = false>(
  options?: Options<GetGeocodeData, ThrowOnError>,
): RequestResult<GetGeocodeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetGeocodeResponses, unknown, ThrowOnError>({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/geocode",
    ...options,
  });

/**
 * Solve a route optimization problem
 *
 *
 * Start by reading the [introduction](#tag/Route-Optimization-API) to the Route Optimization API.
 *
 * To solve a new vehicle routing problem, make a HTTP POST to this URL
 *
 * ```
 * https://graphhopper.com/api/1/vrp?key=<your_key>
 * ```
 *
 * It returns the solution to this problem in the JSON response.
 *
 * Please note that this endpoint is well suited for solving smaller problems.
 * Larger vehicle routing problems that take longer than 10 seconds to solve cannot be processed using this endpoint.
 * To solve them, please use the [batch mode URL](#operation/asyncVRP) instead.
 *
 */
export const solveVrp = <ThrowOnError extends boolean = false>(
  options: Options<SolveVrpData, ThrowOnError>,
): RequestResult<SolveVrpResponses, SolveVrpErrors, ThrowOnError> =>
  (options.client ?? client).post<
    SolveVrpResponses,
    SolveVrpErrors,
    ThrowOnError
  >({
    responseTransformer: solveVrpResponseTransformer,
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/vrp",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Submit a route optimization job
 *
 *
 * To solve a vehicle routing problem, perform the following steps:
 *
 * 1.) Make a HTTP POST to this URL
 *
 * ```
 * https://graphhopper.com/api/1/vrp/optimize?key=<your_key>
 * ```
 *
 * It returns a job id (`job_id`).
 *
 * 2.) Take the job id and fetch the solution for the vehicle routing problem from this URL:
 *
 * ```
 * https://graphhopper.com/api/1/vrp/solution/<job_id>?key=<your_key>
 * ```
 *
 * We recommend querying the solution every 500ms until it returns 'status=finished'.
 *
 * **Note**: Since the workflow is more complex and you lose some time fetching the solution, you should prefer
 * the [synchronous endpoint](#operation/solveVRP) when possible. Use the batch mode only for long-running problems.
 *
 */
export const asyncVrp = <ThrowOnError extends boolean = false>(
  options: Options<AsyncVrpData, ThrowOnError>,
): RequestResult<AsyncVrpResponses, AsyncVrpErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AsyncVrpResponses,
    AsyncVrpErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/vrp/optimize",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Retrieve solution of a route optimization job
 *
 *
 * Take the job id and fetch the solution for the vehicle routing problem from this URL:
 *
 * ```
 * https://graphhopper.com/api/1/vrp/solution/<job_id>?key=<your_key>
 * ```
 *
 * You get the job id by sending a vehicle routing problem to the [batch mode URL](#operation/asyncVRP).
 *
 */
export const getSolution = <ThrowOnError extends boolean = false>(
  options: Options<GetSolutionData, ThrowOnError>,
): RequestResult<GetSolutionResponses, GetSolutionErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetSolutionResponses,
    GetSolutionErrors,
    ThrowOnError
  >({
    responseTransformer: getSolutionResponseTransformer,
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/vrp/solution/{jobId}",
    ...options,
  });

/**
 * Solve a clustering problem
 *
 *
 * The Cluster endpoint is used with a POST request towards
 * `https://graphhopper.com/api/1/cluster?key=<your_key>`. The solution will be provided in the JSON response.
 * Please note that for problems that take longer than 10 seconds a bad request error is returned.
 * In this case please use the asynchronous [Batch Cluster Endpoint](#operation/asyncClusteringProblem) instead.
 *
 */
export const solveClusteringProblem = <ThrowOnError extends boolean = false>(
  options: Options<SolveClusteringProblemData, ThrowOnError>,
): RequestResult<
  SolveClusteringProblemResponses,
  SolveClusteringProblemErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SolveClusteringProblemResponses,
    SolveClusteringProblemErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/cluster",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Submit a clustering job
 *
 *
 * Prefer the [synchronous endpoint](#operation/solveClusteringProblem) and use this Batch Cluster endpoint for
 * long running problems only. The work flow is asynchronous:
 *
 * - send a POST request towards `https://graphhopper.com/api/1/cluster/calculate?key=<your_key>` and fetch the job_id.
 * - poll the solution every 500ms until it gives `status=finished`. Do this with a GET request
 * towards `https://graphhopper.com/api/1/cluster/solution/<job_id>?key=<your_key>`.
 *
 */
export const asyncClusteringProblem = <ThrowOnError extends boolean = false>(
  options: Options<AsyncClusteringProblemData, ThrowOnError>,
): RequestResult<
  AsyncClusteringProblemResponses,
  AsyncClusteringProblemErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AsyncClusteringProblemResponses,
    AsyncClusteringProblemErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/cluster/calculate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Retrieve solution of a clustering job
 *
 * This endpoint returns the solution of the clustering problems submitted to the [Batch Cluster endpoint](#operation/asyncClusteringProblem).
 * You can fetch it with the job_id, you have been sent.
 *
 */
export const getClusterSolution = <ThrowOnError extends boolean = false>(
  options: Options<GetClusterSolutionData, ThrowOnError>,
): RequestResult<
  GetClusterSolutionResponses,
  GetClusterSolutionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetClusterSolutionResponses,
    GetClusterSolutionErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/cluster/solution/{jobId}",
    ...options,
  });

/**
 * List your custom routing profiles
 */
export const getProfile = <ThrowOnError extends boolean = false>(
  options?: Options<GetProfileData, ThrowOnError>,
): RequestResult<GetProfileResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetProfileResponses, unknown, ThrowOnError>({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/profiles",
    ...options,
  });

/**
 * Create a custom routing profile
 */
export const postProfile = <ThrowOnError extends boolean = false>(
  options: Options<PostProfileData, ThrowOnError>,
): RequestResult<PostProfileResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<PostProfileResponses, unknown, ThrowOnError>({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/profiles",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Submit a profile creation job
 *
 * An alternate endpoint for computing a profile for a large boundary asynchronously, where a request against the regular
 * endpoint would result in a timeout.
 *
 * The request format is the same, but instead of the result, you are given a job identification number that
 * you can use to retrieve the result once it is available.
 *
 */
export const calculateProfile = <ThrowOnError extends boolean = false>(
  options: Options<CalculateProfileData, ThrowOnError>,
): RequestResult<CalculateProfileResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    CalculateProfileResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/profiles/calculate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Retrieve result of a profile creation job
 */
export const getProfileSolution = <ThrowOnError extends boolean = false>(
  options: Options<GetProfileSolutionData, ThrowOnError>,
): RequestResult<GetProfileSolutionResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    GetProfileSolutionResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/profiles/solution/{jobId}",
    ...options,
  });

/**
 * Delete a custom routing profile
 */
export const deleteProfile = <ThrowOnError extends boolean = false>(
  options: Options<DeleteProfileData, ThrowOnError>,
): RequestResult<DeleteProfileResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<
    DeleteProfileResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "query",
        name: "key",
        type: "apiKey",
      },
    ],
    url: "/profiles/{profileId}",
    ...options,
  });
