/* eslint-disable */
// This file is auto-generated by @hey-api/openapi-ts

import type { GetSolutionResponse, SolveVrpResponse } from "./types.gen.js";

const activitySchemaResponseTransformer = (data: any) => {
  if (data.end_date_time) {
    data.end_date_time = new Date(data.end_date_time);
  }
  if (data.arr_date_time) {
    data.arr_date_time = new Date(data.arr_date_time);
  }
  return data;
};

const routeSchemaResponseTransformer = (data: any) => {
  if (data.activities) {
    data.activities = data.activities.map((item: any) =>
      activitySchemaResponseTransformer(item),
    );
  }
  return data;
};

const solutionSchemaResponseTransformer = (data: any) => {
  if (data.routes) {
    data.routes = data.routes.map((item: any) =>
      routeSchemaResponseTransformer(item),
    );
  }
  if (data.unassigned) {
    if (data.unassigned.activities) {
      data.unassigned.activities = data.unassigned.activities.map((item: any) =>
        activitySchemaResponseTransformer(item),
      );
    }
  }
  return data;
};

const responseSchemaResponseTransformer = (data: any) => {
  if (data.solution) {
    data.solution = solutionSchemaResponseTransformer(data.solution);
  }
  return data;
};

export const solveVrpResponseTransformer = async (
  data: any,
): Promise<SolveVrpResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};

export const getSolutionResponseTransformer = async (
  data: any,
): Promise<GetSolutionResponse> => {
  data = responseSchemaResponseTransformer(data);
  return data;
};
